[2022-09-24 15:28:48,481] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: task2_xcom_dag.inaccurate scheduled__2022-09-23T00:00:00+00:00 [queued]>
[2022-09-24 15:28:48,556] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: task2_xcom_dag.inaccurate scheduled__2022-09-23T00:00:00+00:00 [queued]>
[2022-09-24 15:28:48,556] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-24 15:28:48,557] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-24 15:28:48,557] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-24 15:28:48,593] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): inaccurate> on 2022-09-23 00:00:00+00:00
[2022-09-24 15:28:48,602] {standard_task_runner.py:52} INFO - Started process 557 to run task
[2022-09-24 15:28:48,618] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'task2_xcom_dag', 'inaccurate', 'scheduled__2022-09-23T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/task2_xcom_dag.py', '--cfg-path', '/tmp/tmp3_dfc41t', '--error-file', '/tmp/tmpjnzuz2w_']
[2022-09-24 15:28:48,620] {standard_task_runner.py:77} INFO - Job 30: Subtask inaccurate
[2022-09-24 15:28:49,087] {logging_mixin.py:109} INFO - Running <TaskInstance: task2_xcom_dag.inaccurate scheduled__2022-09-23T00:00:00+00:00 [running]> on host fce8fcc31726
[2022-09-24 15:28:50,468] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=task2_xcom_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-09-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-23T00:00:00+00:00
[2022-09-24 15:28:50,485] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-24 15:28:50,628] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-09-24 15:28:50,818] {subprocess.py:85} INFO - Output:
[2022-09-24 15:28:50,981] {subprocess.py:89} INFO - inaccurate
[2022-09-24 15:28:50,982] {subprocess.py:93} INFO - Command exited with return code 0
[2022-09-24 15:28:51,349] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=task2_xcom_dag, task_id=inaccurate, execution_date=20220923T000000, start_date=20220924T152848, end_date=20220924T152851
[2022-09-24 15:28:51,534] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-24 15:28:51,664] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
